<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<UseWPF>true</UseWPF>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="../../src/Sdl1000X.Core/Sdl1000X.Core.csproj" />
		<ProjectReference Include="../../src/Sdl1000X.App/Sdl1000X.App.csproj" />
	</ItemGroup>
</Project>
