<Project>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>0.7.4</Version>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<Deterministic>true</Deterministic>
	</PropertyGroup>
	<PropertyGroup Condition="'$(LabStationEmbed)' == 'true'">
		<BaseIntermediateOutputPath>obj/Embed/</BaseIntermediateOutputPath>
		<BaseOutputPath>bin/Embed/</BaseOutputPath>
		<DefaultItemExcludes>$(DefaultItemExcludes);obj/**;bin/**</DefaultItemExcludes>
	</PropertyGroup>
</Project>
