<Project>
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>14.0</LangVersion>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<Deterministic>true</Deterministic>
		<Version>0.1.0</Version>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugType>embedded</DebugType>
	</PropertyGroup>
</Project>
